In [1]:
import pandas as pd
import numpy as np

### import compost garden spreadsheet

In [2]:
original_df = pd.read_excel("data/complete_log.xlsx")


In [3]:
df = original_df.copy()
df.head()


date dropoffs  lbs lbs_per_dropoff little_friends_lbs total_lbs  \
0 2020-07-18   impute  410         compute               None       410   
1 2020-07-25       75  460        6.133333               None       460   
2 2020-08-03       79  550        6.962025               None       550   
3 2020-08-08       68  510             7.5               None       510   
4 2020-08-15       93  720        7.741935               None       720   

  lf_mon lf_tue lf_wed lf_thu  ... 3_week_temp little_friends_collecting  \
0   None   None   None   None  ...        None                     False   
1   None   None   None   None  ...        None                     False   
2   None   None   None   None  ...        None                     False   
3   None   None   None   None  ...        None                     False   
4   None   None   None   None  ...        None                     False   

  sunday_dropoffs market_collecting  bin_weight_subtracted  \
0           False             False                  False   
1           False             False                  False   
2           False             False                  False   
3           False             False                  False   
4           False             False                  False   

   curbside_collection  temp_data  little_friends_daily_breakdown  notes  \
0                False      False                           False    NaN   
1                False      False                           False    NaN   
2                False      False                           False    NaN   
3                False      False                           False    NaN   
4                False      False                           False    NaN   

   notes_2  
0      NaN  
1      NaN  
2      NaN  
3      NaN  
4      NaN  

[5 rows x 23 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype         
---  ------                          --------------  -----         
 0   date                            145 non-null    datetime64[ns]
 1   dropoffs                        145 non-null    object        
 2   lbs                             145 non-null    object        
 3   lbs_per_dropoff                 144 non-null    object        
 4   little_friends_lbs              145 non-null    object        
 5   total_lbs                       145 non-null    object        
 6   lf_mon                          145 non-null    object        
 7   lf_tue                          145 non-null    object        
 8   lf_wed                          145 non-null    object        
 9   lf_thu                          145 non-null    object        
 10  lf_fri                          145 non-null    object        
 11  1_week

### clean up dataframe, converting strings to numbers/booleans

In [5]:
df.loc[df['dropoffs'] == 'impute', 'dropoffs'] = None
df.loc[df['dropoffs'] == 'None', 'dropoffs'] = None
df['dropoffs'] = pd.to_numeric(df['dropoffs'])


In [6]:
df.loc[df['lbs'] == 'impute', 'lbs'] = None
df.loc[df['lbs'] == 'None', 'lbs'] = None
df['lbs'] = pd.to_numeric(df['lbs'])

In [7]:
df.loc[df['lbs_per_dropoff'] == 'compute', 'lbs_per_dropoff'] = None
df.loc[df['lbs_per_dropoff'] == 'None', 'lbs_per_dropoff'] = None
df['lbs_per_dropoff'] = pd.to_numeric(df['lbs_per_dropoff'])

In [8]:
df.loc[df['little_friends_lbs'] == 'None', 'little_friends_lbs'] = 0 
df['little_friends_lbs'] = pd.to_numeric(df['little_friends_lbs'])


^using 0 so 'NaN' doesn't show up on Tableau graph tooltip for this measure

In [9]:
df.loc[df['total_lbs'] == 'compute', 'total_lbs'] = None
df.loc[df['total_lbs'] == 'None', 'total_lbs'] = None
df['total_lbs'] = pd.to_numeric(df['total_lbs'])


In [10]:
df.loc[df['lf_mon'] == 'None', 'lf_mon'] = None
df['lf_mon'] = pd.to_numeric(df['lf_mon'])

df.loc[df['lf_tue'] == 'None', 'lf_tue'] = None
df['lf_tue'] = pd.to_numeric(df['lf_tue'])

df.loc[df['lf_wed'] == 'None', 'lf_wed'] = None
df['lf_wed'] = pd.to_numeric(df['lf_wed'])

df.loc[df['lf_thu'] == 'None', 'lf_thu'] = None
df['lf_thu'] = pd.to_numeric(df['lf_thu'])

df.loc[df['lf_fri'] == 'None', 'lf_fri'] = None
df['lf_fri'] = pd.to_numeric(df['lf_fri'])


In [11]:
df.loc[df['1_week_temp'] == 'impute', '1_week_temp'] = None
df.loc[df['1_week_temp'] == 'None', '1_week_temp'] = None
df['1_week_temp'] = pd.to_numeric(df['1_week_temp'])

df.loc[df['2_week_temp'] == 'impute', '2_week_temp'] = None
df.loc[df['2_week_temp'] == 'None', '2_week_temp'] = None
df['2_week_temp'] = pd.to_numeric(df['2_week_temp'])

df.loc[df['3_week_temp'] == 'impute', '3_week_temp'] = None
df.loc[df['3_week_temp'] == 'None', '3_week_temp'] = None
df.loc[df['3_week_temp'] == 'None ', '3_week_temp'] = None
df['3_week_temp'] = pd.to_numeric(df['3_week_temp'])


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype         
---  ------                          --------------  -----         
 0   date                            145 non-null    datetime64[ns]
 1   dropoffs                        131 non-null    float64       
 2   lbs                             132 non-null    float64       
 3   lbs_per_dropoff                 122 non-null    float64       
 4   little_friends_lbs              145 non-null    float64       
 5   total_lbs                       132 non-null    float64       
 6   lf_mon                          12 non-null     float64       
 7   lf_tue                          12 non-null     float64       
 8   lf_wed                          12 non-null     float64       
 9   lf_thu                          12 non-null     float64       
 10  lf_fri                          12 non-null     float64       
 11  1_week

### subtracting bin weight from records where bin weight was included in measure

In [13]:
df.loc[df['bin_weight_subtracted'] == False, 'lbs'] -= 10
df.loc[df['bin_weight_subtracted'] == False, 'total_lbs'] -= 10


In [14]:
df = df.drop('bin_weight_subtracted',axis=1)


### impute missing values for dropoffs and lbs column


**linear regression on non-missing values to estimate dropoffs from lbs or vise versa**


In [15]:
temp_df = df[['dropoffs','lbs']].copy()


In [16]:
temp_df = temp_df.dropna()


In [17]:
from sklearn.linear_model import LinearRegression

# Split the data into independent and dependent variables
X = temp_df[['dropoffs']]
y = temp_df['lbs']

# Create an instance of the LinearRegression model
model = LinearRegression(fit_intercept=False)

# Fit the model to the data
model.fit(X, y)

# Print the coefficient and intercept
print("Coefficient:", model.coef_)


Coefficient: [6.35987267]


^**for imputation:<br>
estimated lbs = dropoffs x 6.35<br>
estimated dropoffs = lbs / 6.35**

In [18]:
df.loc[df['lbs'].isna(), 'lbs'] = df['dropoffs'] * 6.35


In [19]:
df.loc[df['dropoffs'].isna(), 'dropoffs'] = df['lbs'] / 6.35


In [20]:
df['lbs_per_dropoff'] = df['lbs']/df['dropoffs']


In [21]:
df[df['lbs_per_dropoff'].isna()]

date  dropoffs  lbs  lbs_per_dropoff  little_friends_lbs  total_lbs  \
14 2020-11-07       NaN  NaN              NaN                 0.0        NaN   
16 2020-11-21       NaN  NaN              NaN                 0.0        NaN   
18 2020-12-05       NaN  NaN              NaN                 0.0        NaN   
92 2022-05-22       NaN  NaN              NaN                 0.0        NaN   

    lf_mon  lf_tue  lf_wed  lf_thu  ...  2_week_temp  3_week_temp  \
14     NaN     NaN     NaN     NaN  ...          NaN          NaN   
16     NaN     NaN     NaN     NaN  ...          NaN          NaN   
18     NaN     NaN     NaN     NaN  ...          NaN          NaN   
92     NaN     NaN     NaN     NaN  ...          NaN          NaN   

    little_friends_collecting  sunday_dropoffs  market_collecting  \
14                      False            False              False   
16                      False            False              False   
18                      False            False              False   
92                      False             True               True   

    curbside_collection  temp_data  little_friends_daily_breakdown  notes  \
14                False      False                           False    NaN   
16                False      False                           False    NaN   
18                False      False                           False    NaN   
92                False      False                           False    NaN   

    notes_2  
14      NaN  
16      NaN  
18      NaN  
92      NaN  

[4 rows x 22 columns]

***^dropoffs and lbs both missing for a record?<br>
impute as average between dropoffs/lbs of records above and below**

In [22]:
df.iloc[13:20]

date  dropoffs     lbs  lbs_per_dropoff  little_friends_lbs  \
13 2020-10-31     174.0  1104.9         6.350000                 0.0   
14 2020-11-07       NaN     NaN              NaN                 0.0   
15 2020-11-14      50.0   317.5         6.350000                 0.0   
16 2020-11-21       NaN     NaN              NaN                 0.0   
17 2020-11-28      82.0   520.7         6.350000                 0.0   
18 2020-12-05       NaN     NaN              NaN                 0.0   
19 2020-12-12     112.0   723.0         6.455357                 0.0   

    total_lbs  lf_mon  lf_tue  lf_wed  lf_thu  ...  2_week_temp  3_week_temp  \
13        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
14        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
15        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
16        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
17        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
18        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
19      723.0     NaN     NaN     NaN     NaN  ...          NaN          NaN   

    little_friends_collecting  sunday_dropoffs  market_collecting  \
13                      False            False              False   
14                      False            False              False   
15                      False            False              False   
16                      False            False              False   
17                      False            False              False   
18                      False            False              False   
19                      False            False              False   

    curbside_collection  temp_data  little_friends_daily_breakdown  notes  \
13                False      False                           False    NaN   
14                False      False                           False    NaN   
15                False      False                           False    NaN   
16                False      False                           False    NaN   
17                False      False                           False    NaN   
18                False      False                           False    NaN   
19                False      False                           False    NaN   

    notes_2  
13      NaN  
14      NaN  
15      NaN  
16      NaN  
17      NaN  
18      NaN  
19      NaN  

[7 rows x 22 columns]

In [23]:
df.loc[14,'dropoffs'] = (174 + 50)/2
df.loc[16,'dropoffs'] = (50+82)/2
df.loc[18,'dropoffs'] = (82+112)/2

In [24]:
df.loc[14,'lbs_per_dropoff'] =  6.35
df.loc[16,'lbs_per_dropoff'] =  6.35
df.loc[18,'lbs_per_dropoff'] =  6.35

In [25]:
df.loc[14,'lbs'] =  6.35 * ((174 + 50)/2)
df.loc[16,'lbs'] =  6.35 * ((50+82)/2)
df.loc[18,'lbs'] =  6.35 * ((82+112)/2)

In [26]:
df.iloc[91:94]

date  dropoffs    lbs  lbs_per_dropoff  little_friends_lbs  \
91 2022-05-15      86.0  546.1             6.35                 0.0   
92 2022-05-22       NaN    NaN              NaN                 0.0   
93 2022-05-29      55.0  308.0             5.60                 0.0   

    total_lbs  lf_mon  lf_tue  lf_wed  lf_thu  ...  2_week_temp  3_week_temp  \
91        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
92        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
93      308.0     NaN     NaN     NaN     NaN  ...          NaN          NaN   

    little_friends_collecting  sunday_dropoffs  market_collecting  \
91                      False             True               True   
92                      False             True               True   
93                      False             True               True   

    curbside_collection  temp_data  little_friends_daily_breakdown  notes  \
91                False      False                           False    NaN   
92                False      False                           False    NaN   
93                False      False                           False    NaN   

    notes_2  
91      NaN  
92      NaN  
93      NaN  

[3 rows x 22 columns]

In [27]:
df.loc[92,'dropoffs'] = (86 + 55)/2
df.loc[92,'lbs_per_dropoff'] =  6.35
df.loc[92,'lbs'] =  6.35 * ((86 + 55)/2)
df.iloc[91:94]

date  dropoffs      lbs  lbs_per_dropoff  little_friends_lbs  \
91 2022-05-15      86.0  546.100             6.35                 0.0   
92 2022-05-22      70.5  447.675             6.35                 0.0   
93 2022-05-29      55.0  308.000             5.60                 0.0   

    total_lbs  lf_mon  lf_tue  lf_wed  lf_thu  ...  2_week_temp  3_week_temp  \
91        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
92        NaN     NaN     NaN     NaN     NaN  ...          NaN          NaN   
93      308.0     NaN     NaN     NaN     NaN  ...          NaN          NaN   

    little_friends_collecting  sunday_dropoffs  market_collecting  \
91                      False             True               True   
92                      False             True               True   
93                      False             True               True   

    curbside_collection  temp_data  little_friends_daily_breakdown  notes  \
91                False      False                           False    NaN   
92                False      False                           False    NaN   
93                False      False                           False    NaN   

    notes_2  
91      NaN  
92      NaN  
93      NaN  

[3 rows x 22 columns]

In [28]:
df.loc[df['total_lbs'].isna(),'total_lbs'] = df['lbs']


### impute missing values for temperature

In [29]:
df[126:129][['1_week_temp','2_week_temp','3_week_temp']]

1_week_temp  2_week_temp  3_week_temp
126        118.0        140.0          NaN
127         85.0          NaN        135.0
128          NaN        130.0        138.0

**^ 1 row needs first-week imputed, 1 needs second-week imputed, 1 needs third-week imputed**


**similar strategy as 'lbs' & 'dropoffs' linear regression**<br> 
**but this time features regression on two features to find the third as target**


In [30]:
temp_df = df[['1_week_temp','2_week_temp','3_week_temp']].copy()


In [31]:
temp_df = temp_df.dropna()


In [32]:
# Split the data into independent and dependent variables
X = temp_df[['1_week_temp','2_week_temp']]
y = temp_df['3_week_temp']

# Create an instance of the LinearRegression model
model = LinearRegression(fit_intercept=False)

# Fit the model to the data
model.fit(X, y)

# Print the coefficient and intercept
print("Features:", model.feature_names_in_)
print("Coefficient:", model.coef_)


Features: ['1_week_temp' '2_week_temp']
Coefficient: [0.19550514 0.83923444]


**^first_week(.196) + second_week(.839) == third_week**

In [33]:
# Split the data into independent and dependent variables
X = temp_df[['1_week_temp','3_week_temp']]
y = temp_df['2_week_temp']

# Create an instance of the LinearRegression model
model = LinearRegression(fit_intercept=False)

# Fit the model to the data
model.fit(X, y)

# Print the coefficient and intercept
print("Features:", model.feature_names_in_)
print("Coefficient:", model.coef_)


Features: ['1_week_temp' '3_week_temp']
Coefficient: [0.36625956 0.68435863]


**^first_week(.366) + third_week(.684) == second_week**

In [34]:
# Split the data into independent and dependent variables
X = temp_df[['2_week_temp','3_week_temp']]
y = temp_df['1_week_temp']

# Create an instance of the LinearRegression model
model = LinearRegression(fit_intercept=False)

# Fit the model to the data
model.fit(X, y)

# Print the coefficient and intercept
print("Features:", model.feature_names_in_)
print("Coefficient:", model.coef_)


Features: ['2_week_temp' '3_week_temp']
Coefficient: [0.57468194 0.25014811]


**^second_week(.575) + third_week(.250) == first_week**

In [35]:
df.loc[126,'3_week_temp'] = (df.loc[126,'1_week_temp']*0.196) + (df.loc[126,'2_week_temp']*0.839)
df.loc[126,'3_week_temp']

140.588

In [36]:
df.loc[127,'2_week_temp'] = (df.loc[127,'1_week_temp']*0.366) + (df.loc[127,'3_week_temp']*0.684)
df.loc[127,'2_week_temp']

123.45

In [37]:
df.loc[128,'1_week_temp'] = (df.loc[128,'2_week_temp']*0.575) + (df.loc[128,'3_week_temp']*0.250)
df.loc[128,'1_week_temp']

109.25

In [38]:
df[126:129][['1_week_temp','2_week_temp','3_week_temp']]

1_week_temp  2_week_temp  3_week_temp
126       118.00       140.00      140.588
127        85.00       123.45      135.000
128       109.25       130.00      138.000

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype         
---  ------                          --------------  -----         
 0   date                            145 non-null    datetime64[ns]
 1   dropoffs                        145 non-null    float64       
 2   lbs                             145 non-null    float64       
 3   lbs_per_dropoff                 145 non-null    float64       
 4   little_friends_lbs              145 non-null    float64       
 5   total_lbs                       145 non-null    float64       
 6   lf_mon                          12 non-null     float64       
 7   lf_tue                          12 non-null     float64       
 8   lf_wed                          12 non-null     float64       
 9   lf_thu                          12 non-null     float64       
 10  lf_fri                          12 non-null     float64       
 11  1_week

### adding weather data (starting from when greenmarket began scrap collection)

**finding date greenmarket started scrap collection:**

In [40]:

# Find the first instance of a value
index = df['market_collecting'].eq(True).idxmax()
df.iloc[index] # index 60, October 9th 2021

date                              2021-10-09 00:00:00
dropoffs                                        102.0
lbs                                             647.7
lbs_per_dropoff                                  6.35
little_friends_lbs                                0.0
total_lbs                                       647.7
lf_mon                                            NaN
lf_tue                                            NaN
lf_wed                                            NaN
lf_thu                                            NaN
lf_fri                                            NaN
1_week_temp                                       NaN
2_week_temp                                       NaN
3_week_temp                                       NaN
little_friends_collecting                       False
sunday_dropoffs                                 False
market_collecting                                True
curbside_collection                             False
temp_data                   

### csv of daily historical weather data downloaded from open-meteo.com

In [41]:

orig_df = pd.read_csv("data/historical_weather.csv")
weather_df = orig_df.copy()

In [42]:
weather_df.head()

latitude                 longitude        elevation   utc_offset_seconds  \
0   40.699997                     -73.9              3.0               -14400   
1        time  temperature_2m_mean (°F)  rain_sum (inch)  snowfall_sum (inch)   
2  2021-10-09                      64.4            0.016                0.000   
3  2021-10-10                      64.2            0.091                0.000   
4  2021-10-11                      64.9            0.000                0.000   

           timezone timezone_abbreviation  
0  America/New_York                   EDT  
1               NaN                   NaN  
2               NaN                   NaN  
3               NaN                   NaN  
4               NaN                   NaN

### cleaning weather dataframe

In [43]:
new_column_names = {'latitude': 'date',
                    'longitude': 'temp',
                    'elevation': 'rain',
                    'utc_offset_seconds': 'snow',
                   }

weather_df = weather_df.rename(columns=new_column_names)
weather_df = weather_df.iloc[2:]
weather_df = weather_df.drop(columns=['timezone','timezone_abbreviation'])
weather_df = weather_df.reset_index(drop=True)

weather_df.head()


date  temp   rain   snow
0  2021-10-09  64.4  0.016  0.000
1  2021-10-10  64.2  0.091  0.000
2  2021-10-11  64.9  0.000  0.000
3  2021-10-12  64.5  0.000  0.000
4  2021-10-13  66.2  0.000  0.000

**finding date when Sunday collection started (from composting df):**

In [44]:
# Find the first instance of a value
index = df['sunday_dropoffs'].eq(True).idxmax()

df.iloc[index] # index 69, December 12th 2021

date                              2021-12-12 00:00:00
dropoffs                                         54.0
lbs                                             385.0
lbs_per_dropoff                               7.12963
little_friends_lbs                                0.0
total_lbs                                       385.0
lf_mon                                            NaN
lf_tue                                            NaN
lf_wed                                            NaN
lf_thu                                            NaN
lf_fri                                            NaN
1_week_temp                                       NaN
2_week_temp                                       NaN
3_week_temp                                       NaN
little_friends_collecting                       False
sunday_dropoffs                                  True
market_collecting                                True
curbside_collection                             False
temp_data                   

**finding sunday collection date (Dec 12th 2021) in weather_df:**

In [45]:
index = weather_df['date'].eq('2021-12-12').idxmax()

weather_df.iloc[index] # index 64


date    2021-12-12
temp          43.5
rain         0.008
snow         0.000
Name: 64, dtype: object

**splitting weather dataframe into seperate dataframes for Saturday pickup and Sunday pickup dates:**

In [46]:
sat_pickup_weather_df = weather_df.iloc[:64]
sun_pickup_weather_df = weather_df.iloc[64:]

sat_pickup_weather_df

date  temp   rain   snow
0   2021-10-09  64.4  0.016  0.000
1   2021-10-10  64.2  0.091  0.000
2   2021-10-11  64.9  0.000  0.000
3   2021-10-12  64.5  0.000  0.000
4   2021-10-13  66.2  0.000  0.000
..         ...   ...    ...    ...
59  2021-12-07  38.3  0.008  0.000
60  2021-12-08  37.3  0.008  0.000
61  2021-12-09  34.3  0.004  0.028
62  2021-12-10  39.9  0.008  0.056
63  2021-12-11  53.9  0.312  0.000

[64 rows x 4 columns]

In [47]:
sun_pickup_weather_df

date  temp   rain   snow
64   2021-12-12  43.5  0.008  0.000
65   2021-12-13  41.4  0.000  0.000
66   2021-12-14  41.8  0.000  0.000
67   2021-12-15  44.2  0.028  0.000
68   2021-12-16  53.7  0.000  0.000
..          ...   ...    ...    ...
592  2023-05-24  61.4  0.012  0.000
593  2023-05-25  59.4  0.000  0.000
594  2023-05-26  61.2  0.000  0.000
595  2023-05-27  63.7  0.000  0.000
596  2023-05-28  65.7  0.000  0.000

[533 rows x 4 columns]

**keeping only Saturdays for Saturday pickup dataframe:**

In [48]:
# keeping only saturdays in sat_pickup_weather_df
sat_pickup_weather_df = sat_pickup_weather_df[sat_pickup_weather_df.index % 7 == 0]
sat_pickup_weather_df = sat_pickup_weather_df.iloc[:-1]
sat_pickup_weather_df

date  temp   rain   snow
0   2021-10-09  64.4  0.016  0.000
7   2021-10-16  68.9  0.394  0.000
14  2021-10-23  56.2  0.024  0.000
21  2021-10-30  60.2  0.229  0.000
28  2021-11-06  44.4  0.000  0.000
35  2021-11-13  48.9  0.212  0.000
42  2021-11-20  39.8  0.000  0.000
49  2021-11-27  36.0  0.000  0.000
56  2021-12-04  39.3  0.000  0.000

**keeping only Sundays for Sunday pickup dataframe:**

In [49]:
# keeping only saturdays in sat_pickup_weather_df
sun_pickup_weather_df = sun_pickup_weather_df.reset_index(drop=True)
sun_pickup_weather_df = sun_pickup_weather_df[sun_pickup_weather_df.index % 7 == 0]
sun_pickup_weather_df

date  temp   rain   snow
0    2021-12-12  43.5  0.008  0.000
7    2021-12-19  39.6  0.084  0.000
14   2021-12-26  42.9  0.000  0.000
21   2022-01-02  49.8  0.378  0.000
28   2022-01-09  32.5  0.199  0.000
..          ...   ...    ...    ...
504  2023-04-30  55.2  1.357  0.000
511  2023-05-07  61.7  0.060  0.000
518  2023-05-14  62.5  0.000  0.000
525  2023-05-21  62.9  0.000  0.000
532  2023-05-28  65.7  0.000  0.000

[77 rows x 4 columns]

**stacking Saturday pickups and Sunday pickups back into one dataframe:**

In [50]:
# stacking sat and sun pickup weather data

sat_and_sun_weather_df = pd.concat([sat_pickup_weather_df,sun_pickup_weather_df], ignore_index=True)


In [51]:
# changing date column type to 'datetime64[ns]' and rest of columns to numeric

sat_and_sun_weather_df['date'] = pd.to_datetime(sat_and_sun_weather_df['date'])
sat_and_sun_weather_df['temp'] = pd.to_numeric(sat_and_sun_weather_df['temp'])
sat_and_sun_weather_df['rain'] = pd.to_numeric(sat_and_sun_weather_df['rain'])
sat_and_sun_weather_df['snow'] = pd.to_numeric(sat_and_sun_weather_df['snow'])
sat_and_sun_weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   date    86 non-null     datetime64[ns]
 1   temp    86 non-null     float64       
 2   rain    86 non-null     float64       
 3   snow    86 non-null     float64       
dtypes: datetime64[ns](1), float64(3)
memory usage: 2.8 KB


In [52]:
# creating boolean columns for significant rain/snow

In [53]:
sat_and_sun_weather_df['significant_rain'] = sat_and_sun_weather_df['rain'] >= .33
sat_and_sun_weather_df['significant_snow'] = sat_and_sun_weather_df['snow'] >= .33

sat_and_sun_weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   date              86 non-null     datetime64[ns]
 1   temp              86 non-null     float64       
 2   rain              86 non-null     float64       
 3   snow              86 non-null     float64       
 4   significant_rain  86 non-null     bool          
 5   significant_snow  86 non-null     bool          
dtypes: bool(2), datetime64[ns](1), float64(3)
memory usage: 3.0 KB


***merging weather dataframe with compost dataframe, starting at the right date (Oct 9 2021, when Greenmarket also started collecting scraps)**

In [54]:

complete_df = pd.merge(df, sat_and_sun_weather_df, on='date', how='left')
complete_df.tail()

date  dropoffs    lbs  lbs_per_dropoff  little_friends_lbs  \
140 2023-04-30      47.0  250.0         5.319149                78.5   
141 2023-05-07      57.0  258.6         4.536842                77.5   
142 2023-05-14      52.0  253.0         4.865385                63.5   
143 2023-05-21      64.0  316.1         4.939063                93.5   
144 2023-05-28      38.0  316.1         8.318421                69.5   

     total_lbs  lf_mon  lf_tue  lf_wed  lf_thu  ...  curbside_collection  \
140      328.5    12.0    17.0    10.5    18.0  ...                 True   
141      336.1    13.0    19.5    16.0    12.0  ...                 True   
142      316.5    16.0    11.0     0.0    13.5  ...                 True   
143      409.6    12.0    18.5    18.0    28.0  ...                 True   
144      302.5    13.0    10.5    18.0    12.0  ...                 True   

     temp_data  little_friends_daily_breakdown  \
140       True                            True   
141       True                            True   
142       True                            True   
143       True                            True   
144       True                            True   

                                       notes  notes_2  temp   rain  snow  \
140                                      NaN      NaN  55.2  1.357   0.0   
141                                      NaN      NaN  61.7  0.060   0.0   
142             week 3 temp not yet measured      NaN  62.5  0.000   0.0   
143       week 2 and 3 temp not yet measured      NaN  62.9  0.000   0.0   
144  week 1, 2 , and 3 temp not yet measured      NaN  65.7  0.000   0.0   

     significant_rain  significant_snow  
140              True             False  
141             False             False  
142             False             False  
143             False             False  
144             False             False  

[5 rows x 27 columns]

### turning Little Friends October 2022 zeros back to NaNs so monthly average can be calculated correctly in Tableau

**finding date when Little Friends collection started:**

In [55]:

# Find the first instance of a value
index = df['little_friends_collecting'].eq(True).idxmax()

complete_df.iloc[index] # index 115, October 30th 2022

date                                     2022-10-30 00:00:00
dropoffs                                                47.0
lbs                                                    249.0
lbs_per_dropoff                                     5.297872
little_friends_lbs                                      70.0
total_lbs                                              319.0
lf_mon                                                   NaN
lf_tue                                                   NaN
lf_wed                                                   NaN
lf_thu                                                   NaN
lf_fri                                                   NaN
1_week_temp                                              NaN
2_week_temp                                              NaN
3_week_temp                                              NaN
little_friends_collecting                               True
sunday_dropoffs                                         True
market_collecting       

In [56]:
#changing October's zeros back to null
complete_df[111:116]

date  dropoffs    lbs  lbs_per_dropoff  little_friends_lbs  \
111 2022-10-02      55.0  246.0         4.472727                 0.0   
112 2022-10-09      46.0  300.9         6.541304                 0.0   
113 2022-10-16      68.0  316.1         4.648529                 0.0   
114 2022-10-23      44.0  257.6         5.854545                 0.0   
115 2022-10-30      47.0  249.0         5.297872                70.0   

     total_lbs  lf_mon  lf_tue  lf_wed  lf_thu  ...  curbside_collection  \
111      246.0     NaN     NaN     NaN     NaN  ...                False   
112      300.9     NaN     NaN     NaN     NaN  ...                False   
113      316.1     NaN     NaN     NaN     NaN  ...                False   
114      257.6     NaN     NaN     NaN     NaN  ...                False   
115      319.0     NaN     NaN     NaN     NaN  ...                False   

     temp_data  little_friends_daily_breakdown                       notes  \
111      False                           False                         NaN   
112      False                           False                         NaN   
113      False                           False                         NaN   
114      False                           False                         NaN   
115      False                           False  around 100 little friends    

     notes_2  temp   rain  snow  significant_rain  significant_snow  
111      NaN  56.2  0.316   0.0             False             False  
112      NaN  51.6  0.000   0.0             False             False  
113      NaN  57.5  0.000   0.0             False             False  
114      NaN  56.3  0.076   0.0             False             False  
115      NaN  51.3  0.000   0.0             False             False  

[5 rows x 27 columns]

In [57]:
complete_df.at[111, 'little_friends_lbs'] = None
complete_df.at[112, 'little_friends_lbs'] = None
complete_df.at[113, 'little_friends_lbs'] = None
complete_df.at[114, 'little_friends_lbs'] = None
complete_df[111:116]

date  dropoffs    lbs  lbs_per_dropoff  little_friends_lbs  \
111 2022-10-02      55.0  246.0         4.472727                 NaN   
112 2022-10-09      46.0  300.9         6.541304                 NaN   
113 2022-10-16      68.0  316.1         4.648529                 NaN   
114 2022-10-23      44.0  257.6         5.854545                 NaN   
115 2022-10-30      47.0  249.0         5.297872                70.0   

     total_lbs  lf_mon  lf_tue  lf_wed  lf_thu  ...  curbside_collection  \
111      246.0     NaN     NaN     NaN     NaN  ...                False   
112      300.9     NaN     NaN     NaN     NaN  ...                False   
113      316.1     NaN     NaN     NaN     NaN  ...                False   
114      257.6     NaN     NaN     NaN     NaN  ...                False   
115      319.0     NaN     NaN     NaN     NaN  ...                False   

     temp_data  little_friends_daily_breakdown                       notes  \
111      False                           False                         NaN   
112      False                           False                         NaN   
113      False                           False                         NaN   
114      False                           False                         NaN   
115      False                           False  around 100 little friends    

     notes_2  temp   rain  snow  significant_rain  significant_snow  
111      NaN  56.2  0.316   0.0             False             False  
112      NaN  51.6  0.000   0.0             False             False  
113      NaN  57.5  0.000   0.0             False             False  
114      NaN  56.3  0.076   0.0             False             False  
115      NaN  51.3  0.000   0.0             False             False  

[5 rows x 27 columns]

### save complete dataframe to csv ###

In [58]:
complete_df = complete_df.reset_index(drop=True)
complete_df

date   dropoffs    lbs  lbs_per_dropoff  little_friends_lbs  \
0   2020-07-18  62.992126  400.0         6.350000                 0.0   
1   2020-07-25  75.000000  450.0         6.000000                 0.0   
2   2020-08-03  79.000000  540.0         6.835443                 0.0   
3   2020-08-08  68.000000  500.0         7.352941                 0.0   
4   2020-08-15  93.000000  710.0         7.634409                 0.0   
..         ...        ...    ...              ...                 ...   
140 2023-04-30  47.000000  250.0         5.319149                78.5   
141 2023-05-07  57.000000  258.6         4.536842                77.5   
142 2023-05-14  52.000000  253.0         4.865385                63.5   
143 2023-05-21  64.000000  316.1         4.939063                93.5   
144 2023-05-28  38.000000  316.1         8.318421                69.5   

     total_lbs  lf_mon  lf_tue  lf_wed  lf_thu  ...  curbside_collection  \
0        400.0     NaN     NaN     NaN     NaN  ...                False   
1        450.0     NaN     NaN     NaN     NaN  ...                False   
2        540.0     NaN     NaN     NaN     NaN  ...                False   
3        500.0     NaN     NaN     NaN     NaN  ...                False   
4        710.0     NaN     NaN     NaN     NaN  ...                False   
..         ...     ...     ...     ...     ...  ...                  ...   
140      328.5    12.0    17.0    10.5    18.0  ...                 True   
141      336.1    13.0    19.5    16.0    12.0  ...                 True   
142      316.5    16.0    11.0     0.0    13.5  ...                 True   
143      409.6    12.0    18.5    18.0    28.0  ...                 True   
144      302.5    13.0    10.5    18.0    12.0  ...                 True   

     temp_data  little_friends_daily_breakdown  \
0        False                           False   
1        False                           False   
2        False                           False   
3        False                           False   
4        False                           False   
..         ...                             ...   
140       True                            True   
141       True                            True   
142       True                            True   
143       True                            True   
144       True                            True   

                                       notes  notes_2  temp   rain  snow  \
0                                        NaN      NaN   NaN    NaN   NaN   
1                                        NaN      NaN   NaN    NaN   NaN   
2                                        NaN      NaN   NaN    NaN   NaN   
3                                        NaN      NaN   NaN    NaN   NaN   
4                                        NaN      NaN   NaN    NaN   NaN   
..                                       ...      ...   ...    ...   ...   
140                                      NaN      NaN  55.2  1.357   0.0   
141                                      NaN      NaN  61.7  0.060   0.0   
142             week 3 temp not yet measured      NaN  62.5  0.000   0.0   
143       week 2 and 3 temp not yet measured      NaN  62.9  0.000   0.0   
144  week 1, 2 , and 3 temp not yet measured      NaN  65.7  0.000   0.0   

     significant_rain  significant_snow  
0                 NaN               NaN  
1                 NaN               NaN  
2                 NaN               NaN  
3                 NaN               NaN  
4                 NaN               NaN  
..                ...               ...  
140              True             False  
141             False             False  
142             False             False  
143             False             False  
144             False             False  

[145 rows x 27 columns]

In [59]:
complete_df.to_csv("data/complete_csv.csv")